config/routes.rb
Planner::Application.routes.draw do

  root 'users#new'

  resources :user_sessions, only: [:new, :create, :destroy]
  get 'login', to: 'user_sessions#new', as: :login
  get 'logout', to: 'user_sessions#destroy', as: :logout

  resources :users, only: [:new, :create] do
    resources :days, only: [:show]
  end
  resources :notes, only: [:new, :create]
  resources :track_categories, only: [:new, :create]
  resources :trackables, only: [:new, :create]

end

app/models/day.rb
class Day < ActiveRecord::Base
  belongs_to :user
  has_many :notes
  has_many :trackables

  extend FriendlyId
  friendly_id :date

  def display_string
    date.strftime("%A, %B %d")
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  belongs_to :day

  has_many :note_tags
  has_many :tag_categories, through: :note_tags

end

app/models/note_tag.rb
class NoteTag < ActiveRecord::Base
  belongs_to :tag_category
  belongs_to :note
end

app/models/tag_category.rb
class TagCategory < ActiveRecord::Base
  has_many :note_tags
  has_many :trackable_tags
end

app/models/track_category.rb
class TrackCategory < ActiveRecord::Base
  has_many :trackables

end

app/models/trackable.rb
class Trackable < ActiveRecord::Base
  belongs_to :user
  belongs_to :day
  belongs_to :track_category

  has_many :trackable_tags
  has_many :tag_categories, through: :trackable_tags
end

app/models/trackable_tag.rb
class TrackableTag < ActiveRecord::Base
  belongs_to :tag_category
  belongs_to :trackable
end

app/models/user.rb
require 'bcrypt'

# password stuff taken from http://www.therailsway.com/2009/8/3/users-and-passwords/
# very helpful!
class User < ActiveRecord::Base
  has_many :days
  has_many :notes
  has_many :trackables

  extend FriendlyId

  def self.number_of_users_with_name(first, last)
    User.where(first_name: first, last_name: last).select do |user|
      user.friendly_id =~ /^#{first.downcase}_#{last.downcase}/
    end.count
  end

  friendly_id :url_name, use: :slugged

  def url_name
    #check for reserved names
    case first_name.parameterize
    when 'new' then 'new2'
    when 'edit' then 'edit2'
    else generate_unique_name
    end
  end

  def generate_unique_name
    attempts = [first_name.downcase,
                "#{first_name.downcase}-#{last_name.downcase}",
                "#{first_name.downcase}_#{last_name.downcase}"]
    i = 0
    while i < attempts.length && User.friendly.exists?(attempts[i])
      i += 1
    end
    if (i < attempts.length)
      attempts[i]
    else
      "#{first_name.downcase}_#{last_name.downcase}_#{User.number_of_users_with_name(first_name, last_name)}"
    end
  end

  # Create two virtual (in memory only) attributes to hold the password and its confirmation.
  attr_accessor :new_password, :new_password_confirmation

  ### VALIDATIONS ###

  # We need to validate that the user has typed the same password twice
  # but we only want to do the validation if they've opted to change their password.
  validates_confirmation_of :new_password, if: :password_changed?, message: "Passwords don't match"

  validates_uniqueness_of :email, message: 'That email has already been taken'

  before_save :hash_new_password, :if=>:password_changed?

  # By default the form_helpers will set new_password to "",
  # we don't want to go saving this as a password
  def password_changed?
    !@new_password.blank?
  end

  # As is the 'standard' with rails apps we'll return the user record if the
  # password is correct and nil if it isn't.
  def self.authenticate(email, password)
    # Because we use bcrypt we can't do this query in one part, first
    # we need to fetch the potential user
    if user = find_by_email(email)
      # Then compare the provided password against the hashed one in the db.
      if BCrypt::Password.new(user.hashed_password).is_password? password
        # If they match we return the user 
        return user
      end
    end
    # If we get here it means either there's no user with that email, or the wrong
    # password was provided.  But we don't want to let an attacker know which. 
    return nil
  end

  def display_name
    "#{first_name} #{last_name}"
  end

  def today
    Day.find_or_create_by(date: Date.today, user_id: id)
  end

  private
  # This is where the real work is done, store the BCrypt has in the
  # database
  def hash_new_password
    self.hashed_password = BCrypt::Password.create(@new_password)
    @new_password = nil
    @new_password_confirmation = nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authorize

  helper :all

  helper_method :current_user, :current_user_session

  protected

  def authorize
    unless User.find_by_id(session[:user_id])
      redirect_to login_url, notice: "Please log in"
    end
  end

  private

  def current_day
    @current_day ||= Day.find_or_create_by(user_id: current_user.id, date: Date.today)
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

end

app/controllers/days_controller.rb
class DaysController < ApplicationController

  before_filter :set_user_and_day, only: [:show]

  def show
  end

  private

  def set_user_and_day
    @user = User.friendly.find(params[:user_id])
    @day = Day.friendly.find(params[:id])
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def new
    @note = Note.new(id_params)
  end

  def create
    @note = Note.create(note_params.merge(id_params))
    if @note.save
      flash[:notice] = "Note successfully created"
      redirect_to user_day_path(current_user, current_day)
    else
      render action: 'new'
    end
  end

  private

  def id_params
    {
      user_id: current_user.id,
      day_id: Day.find_by_user_id_and_date(current_user.id, Date.today).id
    }
  end

  def note_params
    params.require(:note).permit(:title, :body)
  end
end

app/controllers/track_categories_controller.rb
class TrackCategoriesController < ApplicationController
  def new
    @track_category = TrackCategory.new
  end

  def create
    @track_category = TrackCategory.create(safe_params)
    if @track_category.save
      flash[:notice] = "Succesfully Created Category, add trackable to this category?"
      redirect_to new_trackable_path(track_category_id: @track_category.id)
    else
      render action: 'new'
    end
  end

  private

  def safe_params
    params.require(:track_category).permit(:name)
  end

end

app/controllers/trackables_controller.rb
class TrackablesController < ApplicationController
  def new
    @trackable = Trackable.new
    @track_category_id = params[:track_category_id]
  end

  def create
    @trackable = Trackable.new(safe_params)
    @trackable.user_id = current_user.id
    @trackable.day_id = current_day.id
    if @trackable.save
      flash[:notice] = 'Successfully created trackable'
      redirect_to user_day_path(current_user, current_day)
    else
      render action: 'new'
    end
  end

  private

  def safe_params
    params.require(:trackable).permit(:name, :trackable_qty, :units, :track_category_id)
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :authorize

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user and User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      redirect_to user_day_path(user, current_day)
    else
      redirect_to new_user_session_path, alert: "Invalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: "Successfully logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :set_user, only: [:show]

  skip_filter :authorize, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Successfully registered!"
      redirect_to user_day_path(@user, current_day)
    else
      render action: 'new'
    end
  end

  protected

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :new_password,
                                 :new_password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/days/show.html.erb
<% today = @user.today %>
<h1><%= today.display_string%></h1>

<h2>Notes:</h2>

<% @user.notes.where(day_id: today.id).each do |note| %>
  <div id='<%= note.id %>' class='note'>
    <p class='note_title'><%= note.title %></p>
    <p class='note_body'><%= note.body %></p>
    <ul>
      <% note.tag_categories.each do |tag_category| %>
        <li class='note_tag'><%= tag_category.name %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% TrackCategory.all.each do |track_category| %>
  <div id='<%= track_category.id %>' class='track_category' %>
    <h3><%= track_category.name %></h3>
    <ul>
      <% Trackable.where(user_id: @user.id, track_category: track_category, day_id: today.id).each do |trackable| %>
        <li><%= "#{trackable.name}, #{trackable.trackable_qty} #{trackable.units}" %></li>
      <% end %>
    </ul>
    <%= link_to "add a #{track_category.name}", new_trackable_path(track_category_id: track_category.id) %>
  </div>
<% end %>

<%= link_to "new note", new_note_path %>
<%= link_to "new trackable category", new_track_category_path %>

<p>Logged in as <%= @user.display_name %>, <%= link_to "Logout", logout_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Planner</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<div id='note_form'>
  <%= form_for @note do |n| %>
    <div>
      <%= n.text_field :title, placeholder: 'Title' %>
    </div>
    <div>
      <%= n.text_area :body, placeholder: 'What are you thinking?' %>
    </div>
    <div>
      <%= n.submit 'Create!' %>
    </div>
  <% end %>
</div>

app/views/notes/new.html.erb
<h1>Note on <%= @note.day.display_string %></h1>

<%= render 'form' %>

app/views/track_categories/_form.html.erb
<div id='track_category_form'>
  <%= form_for @track_category do |t| %>
    <div>
      <%= t.text_field :name %>
    </div>

    <div>
      <%= t.submit 'Add Category!'%>
    </div>
  <% end %>
</div>

app/views/track_categories/new.html.erb
<%= render 'form' %>

app/views/trackables/_form.html.erb
<div id='trackable_form'>
  <%= form_for @trackable do |t| %>
    <div>
      <%= t.text_field :name, placeholder: 'Name' %>
    </div>

    <div>
      <%= t.number_field :trackable_qty, placeholder: 'how many?' %>
    </div>

    <div>
      <%= t.text_field :units, placeholder: 'units' %>
    </div>

    <div>
      <%= t.text_field :track_category_id, value: @track_category_id, style: 'display: none;' %>
    <div>
      <%= t.submit 'Add Trackable!'%>
    </div>
  <% end %>
</div>

app/views/trackables/new.html.erb
<%= render 'form' %>

app/views/user_sessions/_form.html.erb
<div class="login_form">
  <% if flash[:alert] %>
    <p id="notice"><%= flash[:alert] %></p>
  <% end %>
  <%= form_tag(user_sessions_path) do %>
    <fieldset>
      <legend>Please Log In</legend>

      <div>
        <%= text_field_tag :email, params[:email], placeholder: 'Email' %>
      </div>

      <div>
        <%= password_field_tag :password, params[:password], placeholder: 'Password' %>
      </div>
      <div>
        <%= submit_tag "Login" %>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/user_sessions/new.html.erb
<%= render 'form' %>

<%= link_to 'Register', new_user_path %>

app/views/users/_form.html.erb
<div id='user_form'>
  <%= form_for @user do |u| %>
    <div>
      <%= u.text_field :first_name, placeholder: 'First Name' %>
    </div>

    <div>
      <%= u.text_field :last_name, placeholder: 'Last Name' %>
    </div>

    <div>
      <%= u.text_field :email, placeholder: 'Email' %>
    </div>
    <ul id='email_errors'>
      <% @user.errors.messages[:email].each do |msg| %>
        <li class='inline-error'><%=msg%></li>
      <% end %>
    </ul>

    <div>
      <%= u.password_field :new_password, placeholder: 'Password' %>
    </div>

    <div>
      <%= u.password_field :new_password_confirmation, placeholder: 'Confirm Password' %>
    </div>
    <ul id='password_errors'>
      <% @user.errors.messages[:new_password_confirmation].each do |msg| %>
        <li class='inline-error'><%=msg%></li>
      <% end.join(',') %>
    </ul>

    <div>
      <%= u.submit %>
    </div>
  <% end %>
</div>
<div id='login'>
  <p>Already a user? <a href='<%= new_user_session_path %>'>Log in</a></p>
</div>